# config.py
import os

# --- Folder Paths ---
WATCH_FOLDER = r"<WATCH_FOLDER_PATH>"
REPORTS_BASE_FOLDER = r"<REPORT_FOLDER_PATH>"
LOG_FILE = r"<LOG_FILE_PATH>"

# --- Email Credentials & Settings ---
GMAIL_APP_PASSWORD = "<YOUR_16_DIGIT_APP_PASSWORD>"
BREVO_API_KEY = "<YOUR_BREVO_V3_API_KEY>"
SENDER_EMAIL = "<YOUR_EMAIL_ADDRESS>"
RECEIVER_EMAILS = ["<RECEIVER_EMAILS_1>", "<RECEIVER_EMAILS_2>"]
CC_EMAILS = ["<CC_EMAILS_1>"]
BCC_EMAILS = ["<BCC_EMAILS_1>"]